### ISSUE TITLE
Figaro doesn't work with Spring (0.7.0 and master)

### ISSUE THREAD

**Issue by sherwinyu** [laserlemon/figaro#138]
Hi, I can't quite get spring and figaro to play nicely:

With Figaro 0.7.0:

```
bundle exec rails c 
> Figaro.env
=> {"TOKEN" => "abcdef"}

> Figaro.env.TOKEN
=> "abcdef"
```

```
bundle exec spring rails c
> Figaro.env
=> {"TOKEN" => "abcdef"}

> Figaro.env.TOKEN
=> NoMethodError: undefined method `TOKEN' for #<Figaro::Env:0x007feb098f2338>
    ...
```

Now if I switch to `gem 'figaro', github: 'laserlemon/figaro'`:

```
bundle exec rails c 
> Figaro.env
=> Figaro::Env

> Figaro.env.TOKEN
=> "abcdef"
```

```
bundle exec spring rails c
> Figaro.env
=> Figaro::ENV

> Figaro.env.TOKEN
=> nil

> Figaro.env.TOKEN!
Figaro::MissingKey: Missing required Figaro configuration key "TOKEN".
```

So it looks like when I'm running with Spring, Figaro isn't loading from application.yml.

I've looked https://github.com/laserlemon/figaro/issues/120 and https://github.com/laserlemon/figaro/issues/107 but they don't quite describe this issue. Any idea what's going on?

I just upgraded to Rails 4.1.1 (from 4.0, but previously it was a Rails 3.2 app, so I'm thinking perhaps something in the config?)

**Comment by Carpela** [comment]
Spring isn't set up to recognise application.yml as important.
If you change application.rb Spring will detect it and automatically restart. 
If you add
config/spring.rb

    Spring.watch "config/application.yml"

And then in a terminal 

     touch config/application.rb
(Just tells spring to reload so it picks up the config above)

Then every time you change application.yml spring will notice and restart.

Hope that helps somebody. Spent 2 hours thinking there was something wrong with my code before I realised that the env variables weren't updating....
