### ISSUE TITLE
Error with empty configurations values

### ISSUE THREAD

**Issue by ghost** [laserlemon/figaro#33]
On versions prior 0.6.X I used to have the following on my application.yml for development environment:

```
AGS_DB_DATABASE: 
AGS_DB_USERNAME: 
AGS_DB_PASSWORD: 
AGS_DB_HOST: 
AGS_DB_PORT:
AGS_DB_SOCKET: 
```

Since the update to 0.6.1 when trying to start the server with this configurations on dev I get:

```
/home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/figaro-0.6.1/lib/figaro/env.rb:8:in `block in method_missing': undefined method `ags_db_database' for #<Figaro::Env:0xa5f5cd0> (NoMethodError)
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/figaro-0.6.1/lib/figaro/env.rb:8:in `fetch'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/figaro-0.6.1/lib/figaro/env.rb:8:in `method_missing'
    from (erb):22:in `<main>'
    from /home/eticus/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/erb.rb:838:in `eval'
    from /home/eticus/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/erb.rb:838:in `result'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/application/configuration.rb:115:in `database_configuration'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.11/lib/active_record/railtie.rb:78:in `block (2 levels) in <class:Railtie>'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:25:in `each'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.11/lib/active_record/railtie.rb:74:in `block in <class:Railtie>'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `instance_exec'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `run'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `each'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `run_initializers'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/application.rb:136:in `initialize!'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/eticus/workspaces/ix-workspace/app-generator-sever/config/environment.rb:5:in `<top (required)>'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
    from /home/eticus/workspaces/ix-workspace/app-generator-sever/config.ru:3:in `block in <main>'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
    from /home/eticus/workspaces/ix-workspace/app-generator-sever/config.ru:in `new'
    from /home/eticus/workspaces/ix-workspace/app-generator-sever/config.ru:in `<main>'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.5/lib/rack/builder.rb:40:in `parse_file'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/commands/server.rb:46:in `app'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.5/lib/rack/server.rb:254:in `start'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/commands/server.rb:70:in `start'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/commands.rb:55:in `block in <top (required)>'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/commands.rb:50:in `tap'
    from /home/eticus/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.11/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

The workaround for now is to do the following:

```
AGS_DB_DATABASE: ""
AGS_DB_USERNAME: ""
AGS_DB_PASSWORD: ""
AGS_DB_HOST: ""
AGS_DB_PORT: ""
AGS_DB_SOCKET: ""
```

Is this an expected functionality for the 0.6.X if it is just close the issue.
Thanks
Enrique
